---
autor:
  vorname: "Jörg"
  nachname: "Hofmann"
  strasse: "Am Schloßpark 78"
  plz: "65203"
  ort: "Wiesbaden"
  tel: "+49 611 507411"
  mobil: "+49 176 27810343"
  fax: "+49 611 94939032"
  mail: "joerg.hofmann@jho-home.de"
project:
  lang: "de-DE"
  title: ""
  subtitle: ""
  pagetitle: ""
  shorttitle: ""
  cover: ""


